### ISSUE TITLE
Project issue

### ISSUE THREAD

**Issue by Samuelincoom** [renad001/ARViewApp#1]
Whats this for?

**Comment by xloli20** [comment]
it's for Final year project in Computer Sciences College

**Comment by Samuelincoom** [comment]
i know.. but what the use?? is it an augmented reality view??
If yes, is it 3d??

**Comment by xloli20** [comment]
yes it's an augmented reality + social media app.. 
no it's in 2D .. maybe future works in 3D

**Comment by Samuelincoom** [comment]
so like 2 people will be chatting with their background that of a camera???

**Comment by xloli20** [comment]
no someone can post something(drawing and it could be text or upload photo) in specific place .. so others can see it.. comment..etc

**Comment by Samuelincoom** [comment]
intersting.. so what makes "augmented reality"??? because from what you are
talking about, it seems you are talking about a picture-only instagram clone

**Comment by xloli20** [comment]
no you can see the post when you open the camera ... maybe drawing in the wall

**Comment by Samuelincoom** [comment]
i get it now... can you send me screenshots of the views when you are free??

**Comment by xloli20** [comment]
[ARV GUI.pptx](https://github.com/renad001/ARViewApp/files/2866283/ARV.GUI.pptx)
this is our expectation of the app how it will looks like

**Comment by Samuelincoom** [comment]
wow! very interesting.. will be keeping an eye on it

**Comment by Samuelincoom** [comment]
is the AR view also location based??

**Comment by xloli20** [comment]
yes, it is 👍

**Comment by Samuelincoom** [comment]
very impressive

**Comment by xloli20** [comment]
Thank you :)
